name: Veracode Scan

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  veracode-sast-task:
    runs-on: ubuntu-latest
    name: Veracode SAST policy scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Download the artifact from the previous workflow
      - name: Download packages artifact
        uses: actions/download-artifact@v3
        with:
          name: Packages
        
      - name: Run Veracode Policy scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "tm_devices"
          createprofile: false
          version: ${{ github.sha }}
          filepath: "packages.zip"
          scantimeout: 30
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
