name: Build and Scan Package

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      package-name:
        description: The name of the package being installed.
        required: true
        type: string

env:
  PACKAGE_NAME: ${{ inputs.package-name || 'tm_devices' }}

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    environment: package-build
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: hynek/build-and-inspect-python-package@v2.8.0
        id: build-pkg
        with:
          attest-build-provenance-github: ${{ !(github.event.pull_request.head.repo.fork || github.event.workflow_call.pull_request.head.repo.fork) && github.actor != 'dependabot[bot]' }}

  veracode-scan:
    name: Veracode SAST Policy Scan
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download packages artifact
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      
      - name: Run Veracode Policy Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "tm_devices"
          createprofile: false
          version: ${{ github.sha }}
          filepath: "/home/runner/work/tm_devices/tm_devices/dist/Packages.zip"
          scantimeout: 30
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
