name: Veracode Scan
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  veracode-sast-task:
    runs-on: ubuntu-latest
    name: Veracode SAST policy scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ZIP source folder
        run: zip -r src.zip src 
      - name: Run Veracode Policy scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "tm_devices"
          createprofile: false
          version: ${{ github.sha }}
          filepath: "src.zip"
          scantimeout: 30
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
